name: 'Publish to Pypi'
description: 'Publish package to Pypi'

runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build Python package
      shell: bash
      run: |
        python setup.py sdist bdist_wheel
        CHECK_VERSION=$(ls dist/*-${GITHUB_REF#refs/tags/}*.tar.gz)

    - name: Publish release distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
