name: Workflow - dev

on:
  push:
    branches:
    - main

jobs:
  local-test:
    if: false
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - id: checkout-code
      uses: actions/checkout@v4
